### ISSUE TITLE
install 出现 ActivityNotFoundException 导致闪退

### ISSUE THREAD

**Issue by shangsd** [czy1121/update#10]
在魅族和小米6.0上遇到了这个问题，确切的说是魅族，看见了日志，小米的没有看见日志，猜应该是一样的问题。在华为手机6.0以上测试没有这个。因为二次定制了下，不确定是不是我这边改完以后的情况。当版本大于23的时候通过捕获这个异常修改intent.setDataAndType为小于23的时候的设置方法（intent.setDataAndType(Uri.fromFile(file),“xxx”)）解决了这个问题,不知道作者那边是不是也有同样的问题。

**Comment by czy1121** [comment]
6.0是api 23，大于23那就是24+应该是7.0的系统吧 - -
能贴一下具体的异常信息吗

**Comment by czy1121** [comment]
刚在腾讯utest上试了魅族(pro6/pro6s/u20/m5/魅蓝e)等5款6.0系统，都没问题
