### ISSUE TITLE
多个provider节点导致manifest合并冲突

### ISSUE THREAD

**Issue by zhangchaoxu** [czy1121/update#13]
如果app引入的多个第三方库都有定义android.support.v4.content.FileProvider，则可能导致合并的时候冲突，建议自定义FileProvider extends android.support.v4.content.FileProvider,然后在类库的的manifest使用这个自定义FileProvider

**Comment by czy1121** [comment]
嗯，已处理

**Comment by zhangchaoxu** [comment]
Thanks
