### ISSUE TITLE
安装新版本后继续提示有更新

### ISSUE THREAD

**Issue by lhhseraph** [czy1121/update#14]
安装新版本后，启动继续提示有更新。代码判断Json里的hasUpdate为true就会一直提示有更新。不管当前是否是最新版本

**Comment by czy1121** [comment]
这个hasUpdate是你的服务端决定的啊，前端只是提供数据发送请求然后根据服务端的结果来执行

**Comment by lhhseraph** [comment]
了解了，谢谢了。
