### ISSUE TITLE
建议增加参数，可以跳过md5检查

### ISSUE THREAD

**Issue by zhangchaoxu** [czy1121/update#17]
在实际的检查更新接口中很有可能没有md5值，而接口又往往不是android开发人员可以变更的。
所以为了可以继续使用这个lib，建议增加一个参数，可以跳过对md5值的检查。

**Comment by czy1121** [comment]
检查md5是为了确定已经正确完整地下载了要更新的apk
不检查的话，可能会使用一个错误或无效的apk去安装

**Comment by czy1121** [comment]
建议你去提出变更接口比较好

**Comment by zhangchaoxu** [comment]
嗯，明白你的意思。
现在网络环境那么差，机场会有dns劫持，被运营商劫持下载成为其他的apk。
但是有时候给出的接口往往不是android开发可以左右的。

anyway 非常感谢提供这个非常好用的库
