### ISSUE TITLE
gradle添加compile之后项目无法编译

### ISSUE THREAD

**Issue by xjqx2z** [czy1121/update#19]
Error:Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed with multiple errors, see logs

**Comment by czy1121** [comment]
logs，可以发出来看看

建议再确认一下是不是引入这个库导致的

**Comment by crazyandcoder** [comment]
我也出现这个问题，不过看log是minSdkVersion为16，而我的项目是14，改成一致的就行了

**Comment by BadDeveloper2022** [comment]
我也出现这个问题，不过看log是minSdkVersion为16，而我的项目是14，改成一致的就行了

**Comment by crazyandcoder** [comment]
@Sabirjan  干嘛学我 ~
