### ISSUE TITLE
强制更新！！！

### ISSUE THREAD

**Issue by shangsd** [czy1121/update#2]
强制更新下载完成弹出自动安装界面，如果取消安装，返回应用界面（未退出），没有拦截用户操作并提示安装，用户任然使用旧版本，感觉不咋合理。

**Comment by czy1121** [comment]
谢谢反馈，目前改成强制更新安装时会退出app，如有更好的处理方法欢迎提出

**Comment by shangsd** [comment]
感觉给出一个带按钮的下载进度提示框更好一些，如果出现网络等原因导致的下载暂停或文件不完整以及MD5校验不合法能够触发从新下载机制或继续下载，这样是不是感觉更好点儿？

**Comment by czy1121** [comment]
支持断点下载的
现在文件下载后会增加`.apk`后缀
校验apk的md5如果不合法会删除apk

如果想要“带按钮的下载进度提示框”可使用UpdateAgent.OnProgressListener定制
