### ISSUE TITLE
提示3010 下载失败 校验错误

### ISSUE THREAD

**Issue by ljackChen001** [czy1121/update#25]
_提示3010 下载失败 校验错误 这个哪个地方校验失败了啊！
UpdateManager.setDebuggable(false);
UpdateManager.setWifiOnly(false);
UpdateManager.setUrl(mCheckUrl, getChannel());
UpdateManager.check(this);
check(false, true, false, false, true, 998);
UpdateManager.create(this).setUrl(mCheckUrl).setPostData("token="+getToken()).setManual(isManual).setNotifyId(notifyId).setParser(new IUpdateParser() {
			public UpdateInfo parse(String source) throws Exception {
				UpdateInfo info = new UpdateInfo();
				info.hasUpdate = hasUpdate;
				info.updateContent = "• 支持文字、贴纸、背景音乐，尽情展现欢乐气氛；\n• 两人视频通话支持实时滤镜，丰富滤镜，多彩心情；\n• 图片编辑新增艺术滤镜，一键打造文艺画风；\n• 资料卡新增点赞排行榜，看好友里谁是魅力之王。";
				info.versionCode = App.versionCode;
				info.versionName = versionName;
				info.url = mUpdateUrl;
				info.md5 = "---------------";
				info.size = 10149314;
				info.isForce = isForce;
				info.isIgnorable = isIgnorable;
				info.isSilent = isSilent;
				return info;
			}
		}).check();

 public String getChannel() {
		      String channel = null;
		      try {
		          ApplicationInfo ai = getPackageManager().getApplicationInfo(getPackageName(), PackageManager.GET_META_DATA);
		          channel = ai.metaData.getString("UMENG_CHANNEL");
		          if (channel == null) {
		              channel = String.valueOf(ai.metaData.getInt("UMENG_CHANNEL"));
		          }
		      } catch (NameNotFoundException e) {
		         e.printStackTrace();
		     }
		    
		    return  channel;
		 }

这是集成的代码

**Comment by czy1121** [comment]
info.md5是apk文件内容的md5，通常由服务器获取apk文件md5并返回

**Comment by ljackChen001** [comment]
我这个MD5填的是keystore 的MD5

**Comment by ljackChen001** [comment]
{
    "responseCode": 0,
    "responseDescription": "操作成功",
    "responseData": {
        "codeVersion": "2",
        "name": "1.0.17",
        "url": "al/static/al.apk",
        "logs": "static/uploads/vehicleInfo/201703181441316159925.png"
    }
}

服务器就只返回这些

**Comment by czy1121** [comment]
检查md5是为了确定已经正确完整地下载了要更新的apk
你应该跟服务端协商要求其返回md5

**Comment by czy1121** [comment]
是apk文件的md5，不是keystore的

**Comment by ljackChen001** [comment]
这个后台获取apk文件MD5怎么获取哇，都是新手

**Comment by ljackChen001** [comment]
public static String getFileMD5(File file) {  
        if (!file.exists() || !file.isFile()) {  
            return null;  
        }  
        MessageDigest digest = null;  
        FileInputStream in = null;  
        byte buffer[] = new byte[1024];  
        int len;  
        try {  
            digest = MessageDigest.getInstance("MD5");  
            in = new FileInputStream(file);  
            while ((len = in.read(buffer, 0, 1024)) != NEGATIVE_ONE) {  
                digest.update(buffer, 0, len);  
            }  
            in.close();  
        } catch (Exception e) {  
            e.printStackTrace();  
            return null;  
        }  
        BigInteger bigInt = new BigInteger(1, digest.digest());  
        return bigInt.toString(16);  
    }  
  
    /*** 
     * Get MD5 of one file！test ok! 
     *  
     * @param filepath 
     * @return 
     */  
    public static String getFileMD5(String filepath) {  
        File file = new File(filepath);  
        return getFileMD5(file);  
    }

**Comment by ljackChen001** [comment]
这样获取APK文件MD5？

**Comment by jianghejie** [comment]
MD5 在这里是不是多余的？

**Comment by ljackChen001** [comment]
我也这么觉得，我们后台一点不愿意返回，但是被我软磨硬泡的加上了，第一次我以为是key的MD5一脸懵逼

**Comment by czy1121** [comment]
md5始终是是url所表示的apk文件内容的md5
用于防止下载过程中apk内容被修改篡改替换
保障安装的apk是正确完整的
