### ISSUE TITLE
如果当前应用有多个版本没有更新，md5不就对不上了吗？

### ISSUE THREAD

**Issue by ArrsinJiang** [czy1121/update#26]
info.versionCode = 587;
   info.versionName = "v5.8.7";
   info.url = mUpdateUrl;
   info.md5 = "56cf48f10e4cf6043fbf53bbbc4009e3";

**Comment by czy1121** [comment]
如果有多个版本未更新，那就应该返回最新的版本
md5始终是是url所表示的apk文件内容的md5
用于防止下载过程中apk内容被修改篡改替换
