### ISSUE TITLE
md5具体是指？获取APK文件MD5的方法

### ISSUE THREAD

**Issue by yanyusong** [czy1121/update#28]
是发布版apk的keystore解析出来的md5吗？

**Comment by czy1121** [comment]
不是，是apk内容的md5, readme.md有写的

**Comment by yanyusong** [comment]
嗯，我看源码也看到了，但是好像md5是个必填项，请问能不能把md5设成可选项？

**Comment by yanyusong** [comment]
还有就是计算apk内容的md5，这个我找了好一会儿没找到合适的工具来方便的生成md5，请问能不能在这方面再详细说明一下

**Comment by czy1121** [comment]
关于md5

1. 有新版本时，url与md5字段为必填
2. md5始终是是url所表示的**apk文件内容的md5**，不是keystore的md5
3. md5用于确保安装的是完整正确apk，防止下载过程中apk内容被修改篡改替换
4. 不知道如何获取文件md5可参考Update.md5或google/baidu

**Comment by yanyusong** [comment]
1. 最简单的方法，[在线获取文件MD5](http://www.beeee.cn/file_hash/)
2. 喜欢自己写代码的附上[获取File的MD5值的java代码](https://github.com/yanyusong/java-practice/blob/master/FileMD5Get/src/FileMD5Get.java)
