### ISSUE TITLE
手动更新和自动更新问题！！

### ISSUE THREAD

**Issue by shangsd** [czy1121/update#3]
看见有个isManual boolean类型的变量，我的理解是true表示用户手动检查更新，false是自动触发更新，不知道对不对，如果是这样理解，那么当当前为false则表示检测更新的一系列操作对用户是不可感知的，除非有更新则提示。那么3000以下的错误提示是不是不应该给出。

**Comment by czy1121** [comment]
通常app启动时检查更新 isManual为false，用户手动检查更新为true

我觉得出错了应该让用户知道吧

你也可以定制提示行为

``` java
UpdateManager.create(this).setOnFailure(new UpdateAgent.OnFailureListener() {
    @Override
    public void onFailure(UpdateError error) {  
        Toast.makeText(mContext, error.toString(), Toast.LENGTH_LONG).show();
    }
}).check();
```

**Comment by shangsd** [comment]
哦哦，但是我觉得自动检测更新给出错误提示不是很友好，个人观点，希望这个库越来越流弊，哈哈，支持
