### ISSUE TITLE
加入用此库android.permission.WRITE_EXTERNAL_STORAGE 莫名被拒绝

### ISSUE THREAD

**Issue by caojunJackson** [czy1121/update#38]
一旦项目中加入此库,系统就会拒绝android.permission.WRITE_EXTERNAL_STORAGE权限,导致后面再申请此权限不会走初次申请的逻辑 , 希望作者能够解决

**Comment by caojunJackson** [comment]
版本1.0.1出现此问题 , 1.0.0没有此问题

**Comment by czy1121** [comment]
估计是因为我在AndroidManifest.xml中添加了这个

``` xml
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" android:maxSdkVersion="18" />
```

google文档说API19+不再需要这个权限，就是说API<19时需要声明而API19+不需要了
而在API23+上声明了此权限会导致用户可以在设置里禁用此权限

参考：
https://developer.android.com/guide/topics/manifest/uses-permission-element.html    
https://developer.android.com/reference/android/Manifest.permission.html#WRITE_EXTERNAL_STORAGE

**Comment by caojunJackson** [comment]
确实, 刚刚我才试出来
