### ISSUE TITLE
7.0适配

### ISSUE THREAD

**Issue by thewyp** [czy1121/update#4]
没有适配7.0系统

**Comment by czy1121** [comment]
没有7.0的机器，出现什么问题了？

**Comment by thewyp** [comment]
下载完安装崩溃，
7.0以上的在setDataAndType(Uri uri, String type)方法里传递uri要使用FileProvider.getUriForFile(Context context, String authority, File file)，你可以看下http://gold.xitu.io/entry/57bbb1de165abd00662b0f49

**Comment by czy1121** [comment]
谢谢反馈，已修复，虚拟机试过ok，你也试试吧
