### ISSUE TITLE
请求服务器更新信息的时候,没有响应超时怎么办?

### ISSUE THREAD

**Issue by chquanquan** [czy1121/update#42]
我创建了一个progressBar,提示用户,我在检查更新信息.但是服务器没有响应的时候,超时的时候,我想隐藏progressBar,并用toast提示,检查失败....现在我不知道哪里可以回调一下,让我知道check请求超时了....能帮忙解决一下吗?谢谢!!!!!

**Comment by czy1121** [comment]
请求超时应该会回调 OnFailureListener ，用setOnFailure试试
