### ISSUE TITLE
检查更新时候,需要传参..setPostData 不能用,

### ISSUE THREAD

**Issue by chquanquan** [czy1121/update#45]
检查更新时候,需要传参..setPostData 不能用,  有什么方法替代吗?我找不到,求教...真要拼接url吗? 主要是我们的请求是Post方法....

**Comment by czy1121** [comment]
就是用setPostData啊，为啥不能用呢？
如果是QUERY参数就是需要拼接URL

**Comment by chquanquan** [comment]
![tim 20170629102510](https://user-images.githubusercontent.com/14248860/27668715-3ffd2a66-5cb5-11e7-9382-a9fb852ecb82.png)

![pq9 8n g6 a x0 so 1ji](https://user-images.githubusercontent.com/14248860/27668796-bb31415e-5cb5-11e7-834b-6ad31bb9e960.jpg)


就是这样报错,我看代码里也没有setData的方法...点也点不出来.....

**Comment by czy1121** [comment]
https://github.com/czy1121/update/blob/master/library/src/main/java/ezy/boost/update/UpdateManager.java

你是不是用的版本不对，用1.1.1

**Comment by chquanquan** [comment]
是我的问题,我用的版本是1.1.0的...谢谢啦!
