### ISSUE TITLE
静默下载模式

### ISSUE THREAD

**Issue by zengcanxiang** [czy1121/update#5]
感觉静默下载是不是可以下载，然后出现提示安装的框。而不是静默下载后要下一次进来，自动安装。这样用户可以自己选择安不安装，因为现在国内用户对自动安装还是很不友好的

**Comment by czy1121** [comment]
静默下载 主要是希望尽量不中断用户的使用，所以是下次打开app时安装。
现提供`info.isAutoInstall`字段，可以让服务端控制是否在下载完成后自动安装。

**Comment by wb12581** [comment]
为什么我别的都没动只是把.apk地址换成另外的可用地址  走完进度条报校验错误? 求解
