### ISSUE TITLE
提示3010 下载失败 校验错误

### ISSUE THREAD

**Issue by SilasDong** [czy1121/update#52]
没有经常修改，直接克隆项目，在运行的时候报3010错误，我对过项目的apk md5和demo里面的是一致的，运行在Android6.0 虚拟机上和 5.0的真机上都有这个问题，是不是update下载下来还有做什么设置，请指导

**Comment by zhaoxiuyu** [comment]
我的也是

**Comment by gohhng** [comment]
要改代码：
        BigInteger var5 = new BigInteger(1, digest.digest());
//        return String.format("%1$032x", new Object[]{var5});//这是UpdateUtil.java的 226行
        return  var5.toString(16);//<<<改成这样。

**Comment by czy1121** [comment]
@SilasDong @zhaoxiuyu 因demo中mUpdateUrl使用的腾讯动漫的apk地址，但它现在失效了
@gohhng md5是32位的16进制串，开头可能需要0补齐到32位，`.toString(16)`是不会补齐的
