### ISSUE TITLE
借用出现问题

### ISSUE THREAD

**Issue by wb12581** [czy1121/update#6]
为什么我别的都没动只是把.apk地址换成另外的可用地址 走完进度条报校验错误? 求解

**Comment by czy1121** [comment]
对下载的apk进行md5运算后其值就是info.md5，你测试的话info.md5也要改
正式使用时整个info由都服务端返回

**Comment by wb12581** [comment]
刚入门 请问是服务端进行了MD5转码 然后返回APP端 然后APP端再对下载下来的文件进行MD5转码 二者相同校验成功? 我想把MD5加密去掉要怎么改?求大神指点

**Comment by czy1121** [comment]
请看文档，最简单的情况下你只需要设置Url与Channel
并不需要你去转码或校验，UpdateInfo的字段全部由服务端返回

``` java
// 设置默认更新接口地址与渠道 
UpdateManager.setUrl(mCheckUrl, "yyb");
// 进入应用时查询更新
UpdateManager.check(context);
```

如果服务器返回的数据格式不能直接解析成UpdateInfo
这时需要你写一个解析器

``` java
UpdateManager.create(this).setUrl(mCheckUrl).setParser(new UpdateAgent.InfoParser() {
    @Override
    public UpdateInfo parse(String source) throws Exception {
        UpdateInfo info = new UpdateInfo(); 
        // todo
        return info;
    }
}).check();
```

**Comment by wb12581** [comment]
谢谢您的细心解答 其实我是想把MD5加密校验去掉 项目中"info.md5+.apk"用作了文件名 我现在将UpdateUtil.md5()方法去掉了 不做加密 verify(File apk, String md5)中的比较写死 下载成功了 也不会出现校验错误了 我的理解对吧?

**Comment by czy1121** [comment]
md5是文件的指纹，用于检验下载的文件是否完整正确
校验失败表示下载的文件不正确或下载不完整或文件被篡改
你如果觉得无关紧要的话那就去掉吧

**Comment by wb12581** [comment]
哦哦,终于明白md5的作用了,再次谢谢您的细心解答
