### ISSUE TITLE
FileProvider的问题

### ISSUE THREAD

**Issue by ForLovelj** [czy1121/update#61]
java.lang.IllegalArgumentException: Failed to find configured root that contains /storage/0403-0201/Android/data/com.test/cache/5cd045ec48aa50f5a8e8b811a92b0b7b.apk

个别7.0手机会报这个错

**Comment by iielse** [comment]
+1

**Comment by KePeng1019** [comment]
我也遇到了这个问题。

**Comment by KePeng1019** [comment]
@czy1121

**Comment by FiroKuo** [comment]
+1 这个机型也没有找到： HUAWEI honor FRD-AL00

**Comment by FiroKuo** [comment]
@czy1121

**Comment by liylmn** [comment]
自己导入library,然后把update_cache_path.xml中的external-cache-path替换成root-path
