### ISSUE TITLE
为什么会反复跳转安装呀

### ISSUE THREAD

**Issue by lyin3221** [czy1121/update#62]
安装更新完成，下次进入APP又跳转到安装界面

**Comment by yikuo123** [comment]
估计你的app版本号判断没对

**Comment by czy1121** [comment]
@chlseeky 什么机型？系统？

**Comment by lyin3221** [comment]
OPPOA51 Android 5.1.1；我不知道mCheckUrl要怎么写，每次都会返回一个UpdateInfo；我在doCheckFinish这个方法最后一个else里加了个版本号的判断 @czy1121

**Comment by 1th** [comment]
解决了吗？ @chlseeky
