### ISSUE TITLE
无语的bug

### ISSUE THREAD

**Issue by ddt2016** [czy1121/update#65]
使用这个更新库后,会导致,文件写入open failed: EACCES (Permission denied)(ps:拍照存储)
查找了一天,搞得自己差点怀疑人生,
唉,菜鸟啊,啊啊 啊啊啊 啊 啊

**Comment by czy1121** [comment]
不知和这个库有什么关联？

**Comment by pngfi** [comment]
这难道不是你自己没有申请写sd卡权限？

**Comment by pngfi** [comment]
似乎和<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" android:maxSdkVersion="18" />有关系

**Comment by threeloe** [comment]
和下面这个有关系，似乎update的权限声明会覆盖我的app module的权限声明。我用rxpermission去申请存储权限，结果总是不弹出是否允许的对话框，我郁闷了好久，没找到原因，最后去掉这个```
android:maxSdkVersion="18"就好了。
`<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" android:maxSdkVersion="18" />`
