### ISSUE TITLE
mContext.getExternalFilesDir("").getParentFile()报NullPointerException

### ISSUE THREAD

**Issue by manny2011** [czy1121/update#71]
@czy1121 :检测更新时,可否加上判断:如果外置SD卡没挂载或者不可用时,可以使用内部存储.今天应用没有通过小米市场的测试,原因是mContext.getExternalFilesDir("").getParentFile()报NullPointerException.
![_ clw77bf0gxi mxk0snfu](https://user-images.githubusercontent.com/20767496/33645828-bb7035e4-da87-11e7-8c2f-0409581f947a.png)

**Comment by Martinzz** [comment]
+1
