### ISSUE TITLE
查询服务端更新版本号的json格式是怎样的

### ISSUE THREAD

**Issue by 617450941** [czy1121/update#75]
查询服务端更新版本号的json格式是怎样的

**Comment by shopiis** [comment]
$arr = array(
		'hasUpdate' => true,                        // 是否有新版本
		'isSilent' => false,                         // 是否静默下载：有新版本时不提示直接下载
		'isForce' => true,                          // 是否强制安装：不安装无法使用app
		'isAutoInstall' => true,                    // 是否下载完成后自动安装
		'isIgnorable' => false,                     // 是否可忽略该版本
		'updateContent' => "你猜猜更新了什么",
		'versionCode' => 2,                         //版本标识(非常重要)
		'versionName' => "爽歪歪版本",              //版本序号
		'url' => "http://dldir1.qq.com/dmpt/apkSet/qqcomic_android_dm2102.apk",             //新版本APP下载地址
		'md5' => "http://m.xiazai.com",             //MD5效验(防止APP被盗用)
		'size' => 2323232,                              //大小(单位字节)
	);
	
	echo json_encode($arr, JSON_UNESCAPED_UNICODE|JSON_PRETTY_PRINT);  //china
	exit;
