### ISSUE TITLE
有适配8.0的手机吗

### ISSUE THREAD

**Issue by leiduowang** [czy1121/update#82]

**Comment by maopf** [comment]
亲测，可以用。 需要配置 未知来源应用安装权限 管理。
另外对于部分8.0、8.1的手机，在强制安装模式下，可能会出现无法解析安装包的bug，主要是UpdateUtil类 install方法 对于强制安装，执行 System.exit(0) 导致的。

**Comment by GIVEWAYTO** [comment]
> 亲测，可以用。 需要配置 未知来源应用安装权限 管理。
> 另外对于部分8.0、8.1的手机，在强制安装模式下，可能会出现无法解析安装包的bug，主要是UpdateUtil类 install方法 对于强制安装，执行 System.exit(0) 导致的。

那如果修改 System.exit(0)这里的代码呢？

**Comment by abiaodev** [comment]
可以用的，不过需要添加android.permission.REQUEST_INSTALL_PACKAGES权限

**Comment by maopf** [comment]
> > 亲测，可以用。 需要配置 未知来源应用安装权限 管理。
> > 另外对于部分8.0、8.1的手机，在强制安装模式下，可能会出现无法解析安装包的bug，主要是UpdateUtil类 install方法 对于强制安装，执行 System.exit(0) 导致的。
> 
> 那如果修改 System.exit(0)这里的代码呢？
直接注释就可以

**Comment by abiaodev** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
